apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.4.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "172.16.4.0/22",
        "rangeStart": "172.16.5.100",
        "rangeEnd": "172.16.5.200",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "172.16.4.1"
      }
    }'
